theme           : "jekyll-theme-leap-day"
title           : "자전거맨의 블로그"
description     : "자전거맨 - 의 - 개발노트 - 여행노트"
#show_downloads : true
google_analytics:

portfolio_url   : "https://lssang0000.github.io/"
theme: jekyll-theme-leap-day